### PR TITLE
Add Japanese translation

### PR DESCRIPTION
**Pull request by gnuhead-chieb**

### CODE REVIEW

**Comment by gnuhead-chieb** [comment]
https://github.com/yukino-app/yukino/blob/1488641ac7e2526fa66f8840af7776cb94ce2c08/lib/modules/translator/translations/en.dart#L21

https://github.com/yukino-app/yukino/blob/1488641ac7e2526fa66f8840af7776cb94ce2c08/lib/modules/translator/translations/en.dart#L97

https://github.com/yukino-app/yukino/blob/1488641ac7e2526fa66f8840af7776cb94ce2c08/lib/modules/translator/translations/en.dart#L100

It should change strings to like `Episode $variable`.
In Japanese,`第$variable話` is more natural.

**Comment by zyrouge** [comment]
> https://github.com/yukino-app/yukino/blob/1488641ac7e2526fa66f8840af7776cb94ce2c08/lib/modules/translator/translations/en.dart#L21
> 
> https://github.com/yukino-app/yukino/blob/1488641ac7e2526fa66f8840af7776cb94ce2c08/lib/modules/translator/translations/en.dart#L97
> 
> https://github.com/yukino-app/yukino/blob/1488641ac7e2526fa66f8840af7776cb94ce2c08/lib/modules/translator/translations/en.dart#L100
> 
> It should change strings to like `Episode $variable`. In Japanese,`第$variable話` is more natural.

You have to change those outside the translation files. If you want to, you can add it in this PR.

**Comment by gnuhead-chieb** [comment]
> You have to change those outside the translation files. If you want to, you can add it in this PR.

Yeah,I know. but I can't use Dart language well so I don't see where should I change the code for to do this.

**Comment by zyrouge** [comment]
~~I'll do necessary changes for that.~~
I've done enough changes for that (https://github.com/yukino-app/yukino/commit/4d5e2ac5b2e7c3a0bf93f4ff6880370d6055eb21), I'll merge this once the changes are made.

**Comment by zyrouge** [comment]
@gnuhead-chieb You want me to make more changes cus there's a lot of `//?`.

**Comment by zyrouge** [comment]
LGTM.

**Pull request merged**
